---
title: "How to add a data set"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to add a data set}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

- Create a  R file named dataset_*.R in the R/ folder, where * is the name of the dataset.
- Inside that file create 3 functions named `download_*()`, `process_*()` and `dataset_*()`.
  - The `download_*()` function should take 1 argument named `folder_path`. It has 2 tasks, first it should check if the file is already downloaded. If it is already downloaded it should return `invisible()`. If the file isn't at the path it should download the file to said path.
  - The `process_*()` function should take 2 arguments, `folder_path` and `name_path`. `folder_path` denotes the the path to the file returned by `download_*` and `name_path` is the path to where the polished data should live. Main point of `process_*()` is to turn the downloaded file into a .rds file containing a tidy tibble.
  - The `dataset_*()` function should wrap the `load_dataset()`.
- Add the `process_*()` function to the named list `process_functions` in the file process_functions.R.
- Add the `download_*()` function to the named list `download_functions` in the file download_functions.R.
- Modify the `print_info` list in the info.R file.
- Add dataset_*.R to the beginning of the Collate in the DESCRIPTION file.

Data must be downloaded via https per CRAN policy.
